logging:
  level:
    root: INFO
    com.example.sms: DEBUG

management:
  endpoint:
    health:
      show-details: always

sms:
  redis:
    database: ${REDIS_DATABASE:1}
    queue-name: ${REDIS_QUEUE_NAME:sms:incoming:dev}
  behavior:
    delete-sms-after-read: ${DELETE_SMS_AFTER_READ:false}
