logging:
  level:
    root: INFO
    com.example.sms: INFO

management:
  endpoint:
    health:
      show-details: when_authorized

sms:
  redis:
    database: ${REDIS_DATABASE:2}
    queue-name: ${REDIS_QUEUE_NAME:sms:incoming:staging}
  behavior:
    delete-sms-after-read: ${DELETE_SMS_AFTER_READ:false}
