name: sms-serial-reader

x-sms-reader: &sms-reader
  build:
    context: .
    dockerfile: Dockerfile
  image: sms-serial-reader:2.0.0
  restart: unless-stopped
  stop_grace_period: 20s
  logging:
    driver: local
    options:
      max-size: 20m
      max-file: "5"

services:
  sim01:
    <<: *sms-reader
    env_file:
      - ./env/.envsim84832019510
    environment:
      SERIAL_PORT: /dev/modem
    devices:
      - "/dev/ttyUSB0:/dev/modem:rwm"
    volumes:
      - ./logs/sim01:/app/logs

  sim02:
    <<: *sms-reader
    env_file:
      - ./env/.envsim84812943652
    environment:
      SERIAL_PORT: /dev/modem
    devices:
      - "/dev/ttyUSB3:/dev/modem:rwm"
    volumes:
      - ./logs/sim02:/app/logs
